# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Sample pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Run `vagrant validate` on commit
  - repo: https://github.com/ashwin153/pre-commit-vagrant
    rev: v1.1.0
    hooks:
      - id: vagrant-validate
  # Use Commitizen to validate the commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.6.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
