name: Bump Release Version

on:
  push:
    branches:
      - main
    paths:
      - ".cz.yaml"
      - "CHANGELOG.md"

jobs:
  create-new-tag:
    runs-on: ubuntu-latest
    name: "Create new release tag"
    # Checks if the last commit has 'merge' and the branch name 'release-bump-branch' in it
    # Meaning it's the result of merging the release PR
    if: contains(github.event.head_commit.message, 'merge') && contains(github.event.head_commit.message, 'release-bump-branch')
    outputs:
      release_version: ${{ steps.get-release-version-number.outputs.RELEASE_VERSION }}
      incremental_changelog: ${{ steps.incremental-changelog.outputs.INCREMENTAL_CHANGELOG }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install Commitizen
        run: pip install --user -U Commitizen

      - name: Get tag name
        id: get-release-version-number
        run: echo "RELEASE_VERSION=$(cz version -p)" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ steps.get-release-version-number.outputs.RELEASE_VERSION }}"

      - name: Incremental CHANGELOG for Release body
        id: incremental-changelog
        run: |
          # Generate random EOF
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "INCREMENTAL_CHANGELOG<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cz changelog --dry-run v${{ steps.get-release-version-number.outputs.RELEASE_VERSION }})" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

  create-new-release:
    runs-on: ubuntu-latest
    name: "Create new GitHub release"
    needs: create-new-tag
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "v${{ needs.create-new-tag.outputs.release_version }}"
          release_name: "v${{ needs.create-new-tag.outputs.release_version }}"
          body: ${{ needs.create-new-tag.outputs.incremental_changelog }}
          draft: false
          prerelease: true
