name: Bump Release Version

on:
  push:
    branches:
      - main
    paths:
      - ".cz.yaml"
      - "CHANGELOG.md"

jobs:
  check-if-release:
    runs-on: ubuntu-latest
    name: "Check if previous commit was a release PR merge"
    steps:
      - name: Check last commit
        id: check-last-commit
        run: |
          STR="${{ github.event.head_commit.message }}"
          SUB1='merge'
          SUB2='release-bump-branch'
          if [[ "$STR" == *"$SUB1"* ]] && [[ "$STR" == *"$SUB2"* ]]; then
            echo "LAST_COMMIT_VALID=true" >> $GITHUB_OUTPUT
          else
            echo "LAST_COMMIT_VALID=false" >> $GITHUB_OUTPUT
          fi

  create-new-tag:
    runs-on: ubuntu-latest
    name: "Create new release tag"
    needs: check-if-release
    if: needs.check-if-release.outputs.LAST_COMMIT_VALID
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Get tag name
        id: get-release-version-number
        run: echo "RELEASE_VERSION=$(cz version -p)" >> $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ steps.get-release-version-number.outputs.RELEASE_VERSION }}"

  create-new-release:
    runs-on: ubuntu-latest
    name: "Create new GitHub release"
    needs: create-new-tag
    if: needs.check-if-release.outputs.LAST_COMMIT_VALID
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Get tag name
        id: get-release-version-number
        run: echo "RELEASE_VERSION=$(cz version -p)" >> $GITHUB_OUTPUT

      - name: Incremental CHANGELOG for Release body
        id: incremental-changelog
        run: |
          # Generate random EOF
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "INCREMENTAL_CHANGELOG<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cz changelog --dry-run --start-rev v${{ steps.get-release-version-number.outputs.RELEASE_VERSION }})" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "v${{ steps.get-release-version-number.outputs.RELEASE_VERSION }}"
          release_name: "v${{ steps.get-release-version-number.outputs.RELEASE_VERSION }}"
          body: ${{ steps.incremental-changelog.outputs.INCREMENTAL_CHANGELOG }}
          draft: false
          prerelease: true
